### ISSUE TITLE
Entering manifest causes soft lock

### ISSUE THREAD

**Issue by s3rgeant** [DockFrankenstein/SL-Translation-Magizmo#1]
After importing language translation, going to manifest tab locks any interactable things except preview panel

**Comment by ferafiks** [comment]
I've managed to recreate the issue. I'm gonna look into it in a couple of hours

**Comment by ferafiks** [comment]
Okay, turned out that the manifest code caused an infinite loop of reloading the inspector. This will be fixed in the next update
