### ISSUE TITLE
[BUG] Translation string is sometimes cut off

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#11]
**Version:** I used the installer so probably the newest (I don't think there's a way to check the version in the magizmo)

**Describe the Bug**
Write a short description about the bug. Screenshots are welcome
If the translation is not long enough the translation string under it will be cut off
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/f9ff5cff-2619-4902-8a94-c332b30c7568)
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/22be9eab-751b-4e3e-9aaf-fcb2d498d649)
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/77737b71-fb12-485f-802a-501a6a6045ea)
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/2aaa0615-30d5-41bf-830d-920da663118c)

**Steps to reproduce**
- open magizmo
- do things (you know how to reproduce that)

**Comment by Czekoloczek** [comment]
i frogor about the title

**Comment by ferafiks** [comment]
Done. It's gonna be fixed in the next update
