### ISSUE TITLE
[SUGGESTION] Add a version number in the magizmo

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#12]
**Is your feature request related to a problem? Please describe.**
I want to know on which version I am, because i need it to for example report a bug

**Describe the solution you'd like**
Add a version number maybe in the bottom right or in the About > About

**Additional context**

**Comment by ferafiks** [comment]
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/49789311/44f30434-0fae-42f4-9f32-982f3679fcd1)

Done. It's gonna ship with the next update
