### ISSUE TITLE
[SUGGESTION] Add a pop-up warning for when you close the Magizmo whitout saving

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#14]
**Is your feature request related to a problem? Please describe.**
FOR THE LOVE OF GOD I JUST LOST MY PROGRES

**Describe the solution you'd like**
red title :3

**Additional context**
I'd still sex her

**Comment by ferafiks** [comment]
Done. This feature will ship with the next update
