### ISSUE TITLE
[SUGGESTION] The installer should remember the Install path

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#15]
**Is your feature request related to a problem? Please describe.**
I don't want to input the whole "Instal" :trollface:  path when I want to reinstall the magizmo

**Describe the solution you'd like**
Save the path for where the Magizmo is installed somewhere on me comupter

**Additional context**
Cock Frankenstein

**Comment by ferafiks** [comment]
When updating (at least when it's supposed to work) the installer will automatically replace previous instance of sltm. I know last couple of updates didn't work, but from now on there should be no need to download the installer directly from github if you already have sltm on your computer

**Comment by Czekoloczek** [comment]
I've installed the Magizmo with the newest installer on `D:\Czekoloczek\Gry\SLTranslationMagizmo`
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/2d26f13e-02e7-476b-92e9-3e6372bf14cf)
I've Opened up the magizmo again:
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/dc6ac6cd-20de-48ac-b502-f00221c2acdc)
as you can see this doesn't say `D:\Czekoloczek\Gry\SLTranslationMagizmo`
@DockFrankenstein

**Comment by ferafiks** [comment]
Yes, it keeps defaulting to Program Files, but it's not gonna do it when it auto updates. If you want to, you can open command prompt in the same folder where your instance of the magizmo is located and trigger a manual update by running `Uninstall.exe --update`
