### ISSUE TITLE
[SUGGESTION] Add a button to open the magizmo in the installer

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#16]
**Is your feature request related to a problem? Please describe.**
Going to the desktop is too much for me

**Describe the solution you'd like**
I want a button that opens the new freshly installed magizmo :3
Maybe down there next to the Finish button
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/09d3fb85-037b-43b2-9852-f2aa8a513126)

**Additional context**

**Comment by ferafiks** [comment]
Done. In the next update there should be a toggle for that in the installer/updater
