### ISSUE TITLE
[BUG] Preferences are not using current values after installing

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#17]
**Version:** 1.0.0b11

**Describe the Bug**
After installing the magizmo through the installer all Edit > Preferences are using (probably) the defaults (everything is turned off or in is on the minimal value (the UI scale slider is on the minimal value)) instead of using the current

**Steps to reproduce**
Unable to reproduce (probably would need to delete something from appdata but I have no idea where SL Translation magizmo data is stored)

**Comment by ferafiks** [comment]
Done. It's gonna be fixed in the next release
