### ISSUE TITLE
[BUG] Duplicate of Audio Privacy scene

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#19]
**Version:** 1.0.0b18

**Describe the Bug**
Duplicate of Audio Privacy scene that doesn't work

**Steps to reproduce**
Go to:
Menu > Settings > Audio Privacy (this one works)
Menu > Settings > Audio > Privacy (this one doesn't) (personally i like the position of this one more)

**Comment by Czekoloczek** [comment]
Updated to 1.0.0b21 and the bug is still present

**Comment by ferafiks** [comment]
forgof a slash in item generation code, it's gonna be fixed in the next release
