### ISSUE TITLE
[BUG] Array Inspector not updates properly

### ISSUE THREAD

**Issue by s3rgeant** [DockFrankenstein/SL-Translation-Magizmo#2]
# Version: 1.0.0b0

# Steps to reproduce
Switch between tabs that include array inspector
It will show arrays from previous tab.

![Example](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/90758027/d218c18f-4e9e-4800-bf67-406085c22c27)

BTW it will update once you close & open array inspector's items tab

**Comment by ferafiks** [comment]
I've managed to fix the bug. Had to force unity to refresh items when selecting different items
