### ISSUE TITLE
[SUGGESTION] Use steam app protocols

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#3]
Use steam [app protocols](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) in About > SCPSL on steam

**Comment by ferafiks** [comment]
The `About/SCPSL` item is supposed to show information about SCP: Secret Laboratory (if e.g. someone downloads the tool out of curiosity and wants to learn what it's for), not to open the game. Although an "open SL" shortcut seems like a good idea (e.g. `View/Launch SCPSL`)

**Comment by ferafiks** [comment]
In the next release there will be a shortcut to launch sl. I think I can finally mark this one as closed
