### ISSUE TITLE
[SUGGESTION] Make the back button in preferences more contrastable

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#4]
I was trying to leave this page for at least 5 seconds before I found the back button
also, please make it so pressing esc goes back
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/3a2c58b3-4a66-402b-b434-757a14f24704)

**Comment by ferafiks** [comment]
I'm unsure how to add contrast to the button. Making it green will make the window more cluttered. The best solution would be to move the back button, but I don't know where
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/49789311/b37f7cd7-bf4e-4d46-abff-9a35d578aa21)

**Comment by ferafiks** [comment]
![image](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/49789311/3586ef32-9ade-466f-8ae6-a660d91ba81d)

**Comment by ferafiks** [comment]
In the next release the button is moved to the bottom which fixes the issue
