### ISSUE TITLE
[SUGGESTION] Add some way to reset the scene

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#5]
If you go too far with the scene (like the dumbass in the video) you'll have no idea where it is and you'll need to restart the Magizmo
https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/76474182/56d559ba-1924-4b4f-b303-dfd879c9decc

**Comment by ferafiks** [comment]
I think there should just be a limit for how far away you can move outside of the preview canvas until it blocks you

**Comment by ferafiks** [comment]
Newest version now features a reset button
