### ISSUE TITLE
[SUGGESTION] Auto collapsing all categories

### ISSUE THREAD

**Issue by Czekoloczek** [DockFrankenstein/SL-Translation-Magizmo#7]
**Is your feature request related to a problem? Please describe.**
When I open the magizmo I need to a) click View > Collapse all to get to the desired category b) scroll until my fingers fall off

**Describe the solution you'd like**
When you start the magizmo categories should be automatically collapsed.

**Additional context**
i'd still sex her

**Comment by ferafiks** [comment]
I think having the hierarchy expanded by default makes it a little bit easier for new users to understand it, but I've decided to add an optional toggle in preferences to collapse by default
