### ISSUE TITLE
[BUG] the export adds empty lines

### ISSUE THREAD

**Issue by s3rgeant** [DockFrankenstein/SL-Translation-Magizmo#8]
**Version:** 1.0.0b1

**Describe the Bug**
Exporting translation adds an empty line at file start in files where array inspector is used

**Steps to reproduce**
- Export translation
-
![Screenshot_4](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/90758027/8d59b263-b3ed-4cab-86f2-996a8dbc670a)

**Comment by ferafiks** [comment]
Turned out to be an issue with code responsible for adding a prefix to array entries. It will be fixed in the next version, which might release today
