### ISSUE TITLE
"Cause: SCP-018" not only used for dying from 018

### ISSUE THREAD

**Issue by s3rgeant** [DockFrankenstein/SL-Translation-Magizmo#9]
**Version:** 1.0.0b2
not a bug, but anyways:

(instantly killed from falling into a pit)
![Screenshot_6](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/90758027/bb5925d2-01f3-4b8f-bb0e-22b0638653f0)
(did actually died from 018)
![Screenshot_8](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/90758027/c628214c-6f0e-493a-b8f2-352492ccaf0d)
It should say something different but not Cause scp 018
![Screenshot_7](https://github.com/DockFrankenstein/SL-Translation-Magizmo/assets/90758027/72c8f40d-20ad-4c0a-97ac-58d5db2f3bd1)

**Comment by ferafiks** [comment]
Turns out there's all sorts of issues with death reasons translations. Let me know if you notice any other errors. Labeling will be fixed in the next update
